"""
src/sandtable/core/events.py

Event definitions for the event-driven backtesting framework.

All events are immutable dataclasses that flow through the central event queue.
Events are ordered by timestamp for priority queue processing.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import Enum, auto


class EventType(Enum):
    """
    Types of events in the backtesting system.

    Attributes:
        MARKET_DATA: A new price bar (row in the data frame; OHLCV) has arrived from the data handler.
        SIGNAL: The strategy has detected a trading opportunity and wants to go long or short (direction).
        ORDER: A request to buy or sell a specific quantity of shares has been submitted.
        FILL: An order has been executed and the trade is complete with final price and costs.
    """
    MARKET_DATA = auto()
    SIGNAL = auto()
    ORDER = auto()
    FILL = auto()


class Direction(Enum):
    """
    Trading direction for signals, orders, and fills.

    Attributes:
        LONG: Betting the price will go up / buy shares hoping to sell them later at a higher price.
        SHORT: Betting the price will go down / borrow and sell shares hoping to buy them back cheaper.
    """
    LONG = auto()
    SHORT = auto()


class OrderType(Enum):
    """
    Order types supported by the execution simulator.

    Attributes:
        MARKET: Execute immediately at the current market price, guaranteeing a fill but not the price.
        LIMIT: Execute only at a specified price or better, guaranteeing the price but not a fill.
    """
    MARKET = auto()
    LIMIT = auto()


@dataclass(frozen=True)
class MarketDataEvent:
    """
    Market data event containing OHLCV bar data.

    Attributes:
        timestamp: Bar timestamp
        symbol: Ticker symbol
        open: Opening price
        high: High price
        low: Low price
        close: Closing price
        volume: Trading volume
    """
    timestamp: datetime
    symbol: str
    open: float
    high: float
    low: float
    close: float
    volume: float
    event_type: EventType = EventType.MARKET_DATA

    def __lt__(self, other: MarketDataEvent) -> bool:
        """
        Compare events by timestamp for priority queue ordering.
        """
        return self.timestamp < other.timestamp


@dataclass(frozen=True)
class SignalEvent:
    """
    Signal event generated by a strategy.

    Attributes:
        timestamp: Signal generation time
        symbol: Ticker symbol
        direction: LONG or SHORT
        strength: Signal strength (0.0 to 1.0), used for position sizing
    """

    timestamp: datetime
    symbol: str
    direction: Direction
    strength: float = 1.0
    event_type: EventType = EventType.SIGNAL

    def __lt__(self, other: SignalEvent) -> bool:
        """
        Compare events by timestamp for priority queue ordering.
        """
        return self.timestamp < other.timestamp


@dataclass(frozen=True)
class OrderEvent:
    """
    Order event sent to the execution simulator.

    Attributes:
        timestamp: Order submission time
        symbol: Ticker symbol
        direction: LONG (buy) or SHORT (sell)
        quantity: Number of shares
        order_type: MARKET or LIMIT
        limit_price: Price for limit orders (None for market orders)
    """
    timestamp: datetime
    symbol: str
    direction: Direction
    quantity: int
    order_type: OrderType = OrderType.MARKET
    limit_price: float | None = None
    event_type: EventType = EventType.ORDER

    def __lt__(self, other: OrderEvent) -> bool:
        """
        Compare events by timestamp for priority queue ordering.
        """
        return self.timestamp < other.timestamp


@dataclass(frozen=True)
class FillEvent:
    """
    Fill event returned by the execution simulator.

    Attributes:
        timestamp: Fill execution time
        symbol: Ticker symbol
        direction: LONG (bought) or SHORT (sold)
        quantity: Number of shares filled
        fill_price: Actual execution price
        commission: Transaction commission cost
        slippage: Slippage cost (difference from expected price)
        market_impact: Market impact cost
    """
    timestamp: datetime
    symbol: str
    direction: Direction
    quantity: int
    fill_price: float
    commission: float
    slippage: float
    market_impact: float
    event_type: EventType = EventType.FILL

    def __lt__(self, other: FillEvent) -> bool:
        """
        Compare events by timestamp for priority queue ordering.
        """
        return self.timestamp < other.timestamp

    @property
    def total_cost(self) -> float:
        """
        Total transaction cost including commission, slippage, and impact.
        """
        return self.commission + self.slippage + self.market_impact
